services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
      MYSQL_USER: guru
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - ./db-data:/var/lib/mysql    
    networks:
      - mynetwork
  api:
    build: ./api-ser/
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: guru
      DB_PASSWORD: password
      DB_NAME: renewlabour
    networks:
      - mynetwork  
networks:
  mynetwork:
    driver: bridge